pub mod binary_static;
pub mod config_static;
pub mod credential_static;
pub mod dlc_model;
mod edge_ai_common;
pub mod failure_clustering;
pub mod magik_model;
mod model_metadata;
pub mod onnx_model;
pub mod service_runtime;
pub mod tflite_model;
pub mod web_surface_static;

pub use binary_static::BinaryStaticAnalyzer as BinarySecurityAnalyzer;
pub use config_static::ConfigStaticAnalyzer;
pub use credential_static::CredentialStaticAnalyzer;
pub use dlc_model::DLCModelAnalyzer;
pub use failure_clustering::FailureClusteringAnalyzer;
pub use magik_model::MagikModelAnalyzer;
pub use onnx_model::OnnxModelAnalyzer;
pub use service_runtime::ServiceRuntimeAnalyzer;
pub use tflite_model::TFLiteModelAnalyzer;
pub use web_surface_static::WebSurfaceStaticAnalyzer;
