FROM docker.io/library/debian:13-slim@sha256:38a76d01668772e381ad2826d876627c89e7133e2f8a0f5d567306798b0f2a16

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    bc=1.07.1-4 \
    bison=2:3.8.2+dfsg-1+b2 \
    build-essential=12.12 \
    cpio=2.15+dfsg-2 \
    dwarves=1.30-1 \
    flex=2.6.4-8.2+b4 \
    gcc-arm-linux-gnueabi=4:14.2.0-1 \
    gcc-mips-linux-gnu=4:14.2.0-1 \
    gcc-mipsel-linux-gnu=4:14.2.0-1 \
    jq=1.7.1-6+deb13u3 \
    libelf-dev=0.192-4 \
    libssl-dev=3.5.6-1~deb13u2 \
    make=4.4.1-2 \
    xz-utils=5.8.1-1+deb13u1 \
 && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    libc6-dev-armel-cross=2.41-11cross1 \
    libc6-dev-mips-cross=2.40-5cross1 \
    libc6-dev-mipsel-cross=2.40-5cross1 \
 && rm -rf /var/lib/apt/lists/*

COPY kernel/builder/build-kernel.sh /opt/fat/build-kernel.sh
COPY kernel/fixtures/build-initramfs.sh /opt/fat/build-initramfs.sh
COPY kernel/fixtures/init.c /opt/fat/init.c
RUN chmod 0555 /opt/fat/build-kernel.sh /opt/fat/build-initramfs.sh

ENTRYPOINT ["/opt/fat/build-kernel.sh"]
