[package]
name = "fat-toolkit-plugin-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Plugin system type definitions for FAT"
publish = false

[lib]
name = "fat_plugin_api"
path = "src/lib.rs"

[dependencies]
fat_core = { version = "=2.0.0", path = "../fat_core", package = "fat-toolkit-core" }
serde = { version = "1", features = ["derive"] }

[lints]
workspace = true
